-- =====================================================
-- YİSA-S 66 DİREKTÖRLÜK ŞABLONU — TEK DOSYADA
-- Supabase Dashboard → SQL Editor → Yapıştır → Run
-- Önce CREATE TABLE, sonra DELETE, sonra 66 INSERT (icerik DOLU)
-- =====================================================

CREATE TABLE IF NOT EXISTS ceo_templates (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  ad TEXT NOT NULL,
  kategori TEXT NOT NULL,
  icerik JSONB NOT NULL DEFAULT '{}',
  durum TEXT DEFAULT 'aktif',
  olusturan TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ceo_templates_kategori ON ceo_templates(kategori);
CREATE INDEX IF NOT EXISTS idx_ceo_templates_olusturan ON ceo_templates(olusturan);

DELETE FROM ceo_templates WHERE olusturan IN ('CFO','CLO','CHRO','CMO','CTO','CSO','CSPO','COO','CMDO','CCO','CDO','CISO');

-- Eski şema uyumu: template_name NOT NULL ise bu sütunları da doldur
-- (ad -> template_name, icerik -> content, template_type = 'rapor')

-- ─────────────────────────────────────────────────────────────────────────────
-- CFO: 8 şablon
-- ─────────────────────────────────────────────────────────────────────────────
INSERT INTO ceo_templates (ad, kategori, icerik, durum, olusturan, template_name, template_type, content) VALUES
('Kasa Defteri', 'CFO', '{"tip":"tablo","alanlar":["tarih","aciklama","giris","cikis","bakiye","referans_no"],"aciklama":"Günlük kasa hareketleri ve bakiye takibi"}', 'aktif', 'CFO', 'Kasa Defteri', 'rapor', '{"tip":"tablo","alanlar":["tarih","aciklama","giris","cikis","bakiye","referans_no"],"aciklama":"Günlük kasa hareketleri ve bakiye takibi"}'::jsonb),
('Aidat Takip', 'CFO', '{"tip":"tablo","alanlar":["sporcu_adi","donem","tutar","odeme_durumu","vade_tarihi","odeme_tarihi"],"aciklama":"Sporcu aidat ödemeleri ve vade takibi"}', 'aktif', 'CFO', 'Aidat Takip', 'rapor', '{"tip":"tablo","alanlar":["sporcu_adi","donem","tutar","odeme_durumu","vade_tarihi","odeme_tarihi"],"aciklama":"Sporcu aidat ödemeleri ve vade takibi"}'::jsonb),
('Gelir-Gider Raporu', 'CFO', '{"tip":"rapor","alanlar":["donem_baslangic","donem_bitis","gelir_toplam","gider_toplam","net_fark"],"metrikler":["gelir_kategorileri","gider_kategorileri"],"aciklama":"Dönemsel gelir-gider özeti"}', 'aktif', 'CFO', 'Gelir-Gider Raporu', 'rapor', '{"tip":"rapor","alanlar":["donem_baslangic","donem_bitis","gelir_toplam","gider_toplam","net_fark"],"metrikler":["gelir_kategorileri","gider_kategorileri"],"aciklama":"Dönemsel gelir-gider özeti"}'::jsonb),
('Maas Bordrosu', 'CFO', '{"tip":"rapor","alanlar":["personel_adi","brut_maas","kesintiler","net_maas","donem"],"aciklama":"Aylık maaş bordrosu özeti"}', 'aktif', 'CFO', 'Maas Bordrosu', 'rapor', '{"tip":"rapor","alanlar":["personel_adi","brut_maas","kesintiler","net_maas","donem"],"aciklama":"Aylık maaş bordrosu özeti"}'::jsonb),
('Vergi Takip', 'CFO', '{"tip":"rapor","alanlar":["vergi_turu","son_odeme_tarihi","tutar","durum","referans"],"aciklama":"Vergi ödeme takvimi ve durumu"}', 'aktif', 'CFO', 'Vergi Takip', 'rapor', '{"tip":"rapor","alanlar":["vergi_turu","son_odeme_tarihi","tutar","durum","referans"],"aciklama":"Vergi ödeme takvimi ve durumu"}'::jsonb),
('Fatura Sablonu', 'CFO', '{"tip":"belge","alanlar":["fatura_no","musteri_adi","kalemler","kdv_orani","toplam_tutar","vade"],"aciklama":"Standart fatura şablonu"}', 'aktif', 'CFO', 'Fatura Sablonu', 'rapor', '{"tip":"belge","alanlar":["fatura_no","musteri_adi","kalemler","kdv_orani","toplam_tutar","vade"],"aciklama":"Standart fatura şablonu"}'::jsonb),
('Butce Plani', 'CFO', '{"tip":"plan","alanlar":["yil","ay","kalem_adi","planlanan_tutar","gerceklesen_tutar"],"aciklama":"Yıllık/aylık bütçe planı"}', 'aktif', 'CFO', 'Butce Plani', 'rapor', '{"tip":"plan","alanlar":["yil","ay","kalem_adi","planlanan_tutar","gerceklesen_tutar"],"aciklama":"Yıllık/aylık bütçe planı"}'::jsonb),
('Nakit Akis Raporu', 'CFO', '{"tip":"rapor","alanlar":["donem","giris_toplam","cikis_toplam","bakiye_baslangic","bakiye_son"],"aciklama":"Nakit akış özeti"}', 'aktif', 'CFO', 'Nakit Akis Raporu', 'rapor', '{"tip":"rapor","alanlar":["donem","giris_toplam","cikis_toplam","bakiye_baslangic","bakiye_son"],"aciklama":"Nakit akış özeti"}'::jsonb);

-- ─────────────────────────────────────────────────────────────────────────────
-- CLO: 8 şablon
-- ─────────────────────────────────────────────────────────────────────────────
INSERT INTO ceo_templates (ad, kategori, icerik, durum, olusturan, template_name, template_type, content) VALUES
('Franchise Sozlesmesi', 'CLO', '{"tip":"sozlesme","taraflar":["franchise_veren","franchise_alan"],"maddeler":["tanimlar","sure","ucretler","yetkiler","gizlilik","fesih"],"aciklama":"Franchise veren ile alan arasında sözleşme metni"}', 'aktif', 'CLO', 'Franchise Sozlesmesi', 'rapor', '{"tip":"sozlesme","taraflar":["franchise_veren","franchise_alan"],"maddeler":["tanimlar","sure","ucretler","yetkiler","gizlilik","fesih"],"aciklama":"Franchise veren ile alan arasında sözleşme metni"}'::jsonb),
('Personel Is Sozlesmesi', 'CLO', '{"tip":"sozlesme","taraflar":["isveren","isci"],"alanlar":["pozisyon","baslangic_tarihi","maas","calisma_saatleri"],"maddeler":["gorevler","sure","fesih_kosullari"],"aciklama":"İş sözleşmesi şablonu"}', 'aktif', 'CLO', 'Personel Is Sozlesmesi', 'rapor', '{"tip":"sozlesme","taraflar":["isveren","isci"],"alanlar":["pozisyon","baslangic_tarihi","maas","calisma_saatleri"],"maddeler":["gorevler","sure","fesih_kosullari"],"aciklama":"İş sözleşmesi şablonu"}'::jsonb),
('KVKK Aydinlatma', 'CLO', '{"tip":"yasal_metin","maddeler":["veri_sorumlusu","islenen_veriler","amac","haklar","iletisim"],"aciklama":"KVKK aydınlatma metni"}', 'aktif', 'CLO', 'KVKK Aydinlatma', 'rapor', '{"tip":"yasal_metin","maddeler":["veri_sorumlusu","islenen_veriler","amac","haklar","iletisim"],"aciklama":"KVKK aydınlatma metni"}'::jsonb),
('Veli Riza Belgesi', 'CLO', '{"tip":"onam_formu","alanlar":["veli_adi","cocuk_adi","etkinlik_adi","tarih","imza"],"aciklama":"Reşit olmayan için veli onay formu"}', 'aktif', 'CLO', 'Veli Riza Belgesi', 'rapor', '{"tip":"onam_formu","alanlar":["veli_adi","cocuk_adi","etkinlik_adi","tarih","imza"],"aciklama":"Reşit olmayan için veli onay formu"}'::jsonb),
('Gizlilik Politikasi', 'CLO', '{"tip":"yasal_metin","maddeler":["toplanan_veriler","kullanim_amaci","paylasim","saklama_suresi","haklar"],"aciklama":"Gizlilik politikası metni"}', 'aktif', 'CLO', 'Gizlilik Politikasi', 'rapor', '{"tip":"yasal_metin","maddeler":["toplanan_veriler","kullanim_amaci","paylasim","saklama_suresi","haklar"],"aciklama":"Gizlilik politikası metni"}'::jsonb),
('Cerez Politikasi', 'CLO', '{"tip":"yasal_metin","maddeler":["cerez_turleri","kullanim_amaci","yönetim","reddetme"],"aciklama":"Çerez kullanım politikası"}', 'aktif', 'CLO', 'Cerez Politikasi', 'rapor', '{"tip":"yasal_metin","maddeler":["cerez_turleri","kullanim_amaci","yönetim","reddetme"],"aciklama":"Çerez kullanım politikası"}'::jsonb),
('Kullanim Kosullari', 'CLO', '{"tip":"yasal_metin","maddeler":["hizmet_kapsami","kullanici_yukumlulukleri","fikri_mulkiyet","sinirlama","uygulanacak_hukuk"],"aciklama":"Genel kullanım koşulları"}', 'aktif', 'CLO', 'Kullanim Kosullari', 'rapor', '{"tip":"yasal_metin","maddeler":["hizmet_kapsami","kullanici_yukumlulukleri","fikri_mulkiyet","sinirlama","uygulanacak_hukuk"],"aciklama":"Genel kullanım koşulları"}'::jsonb),
('Iade/Iptal Politikasi', 'CLO', '{"tip":"yasal_metin","maddeler":["iptal_suresi","iade_kosullari","islem_suresi","istisnalar"],"aciklama":"İade ve iptal koşulları"}', 'aktif', 'CLO', 'Iade/Iptal Politikasi', 'rapor', '{"tip":"yasal_metin","maddeler":["iptal_suresi","iade_kosullari","islem_suresi","istisnalar"],"aciklama":"İade ve iptal koşulları"}'::jsonb);

-- ─────────────────────────────────────────────────────────────────────────────
-- CHRO: 6 şablon
-- ─────────────────────────────────────────────────────────────────────────────
INSERT INTO ceo_templates (ad, kategori, icerik, durum, olusturan, template_name, template_type, content) VALUES
('Gorev Tanimi', 'CHRO', '{"tip":"belge","alanlar":["pozisyon_adi","departman","rapor_veren","ana_gorevler","yetkiler","nitelikler"],"kriterler":["egitim","deneyim","beceriler"],"aciklama":"Pozisyon görev tanımı"}', 'aktif', 'CHRO', 'Gorev Tanimi', 'rapor', '{"tip":"belge","alanlar":["pozisyon_adi","departman","rapor_veren","ana_gorevler","yetkiler","nitelikler"],"kriterler":["egitim","deneyim","beceriler"],"aciklama":"Pozisyon görev tanımı"}'::jsonb),
('Performans Degerlendirme', 'CHRO', '{"tip":"form","alanlar":["calisan_adi","donem","degerlendiren","puan_toplam"],"kriterler":["is_kalitesi","takim_calismasi","iletisim","hedefler"],"olcek":"1-5","aciklama":"Yıllık performans değerlendirme formu"}', 'aktif', 'CHRO', 'Performans Degerlendirme', 'rapor', '{"tip":"form","alanlar":["calisan_adi","donem","degerlendiren","puan_toplam"],"kriterler":["is_kalitesi","takim_calismasi","iletisim","hedefler"],"olcek":"1-5","aciklama":"Yıllık performans değerlendirme formu"}'::jsonb),
('Izin Takip', 'CHRO', '{"tip":"tablo","alanlar":["personel_adi","izin_turu","baslangic","bitis","gun_sayisi","onay_durumu"],"aciklama":"Yıllık izin ve rapor takibi"}', 'aktif', 'CHRO', 'Izin Takip', 'rapor', '{"tip":"tablo","alanlar":["personel_adi","izin_turu","baslangic","bitis","gun_sayisi","onay_durumu"],"aciklama":"Yıllık izin ve rapor takibi"}'::jsonb),
('Ise Alim Formu', 'CHRO', '{"tip":"form","alanlar":["ad_soyad","pozisyon","egitim","deneyim","referanslar","mulakat_notu"],"aciklama":"İşe alım başvuru ve değerlendirme formu"}', 'aktif', 'CHRO', 'Ise Alim Formu', 'rapor', '{"tip":"form","alanlar":["ad_soyad","pozisyon","egitim","deneyim","referanslar","mulakat_notu"],"aciklama":"İşe alım başvuru ve değerlendirme formu"}'::jsonb),
('Oryantasyon Plani', 'CHRO', '{"tip":"plan","bolumler":["tanisma","tesis_tanitimi","politikalar","sistem_egitimi","hedef_belirleme"],"alanlar":["tarih","konu","sorumlu","tamamlandi"],"aciklama":"Yeni personel oryantasyon planı"}', 'aktif', 'CHRO', 'Oryantasyon Plani', 'rapor', '{"tip":"plan","bolumler":["tanisma","tesis_tanitimi","politikalar","sistem_egitimi","hedef_belirleme"],"alanlar":["tarih","konu","sorumlu","tamamlandi"],"aciklama":"Yeni personel oryantasyon planı"}'::jsonb),
('Disiplin Tutanagi', 'CHRO', '{"tip":"belge","alanlar":["personel_adi","tarih","olay_ozeti","uyari_turu","imza"],"aciklama":"Disiplin uyarı tutanağı"}', 'aktif', 'CHRO', 'Disiplin Tutanagi', 'rapor', '{"tip":"belge","alanlar":["personel_adi","tarih","olay_ozeti","uyari_turu","imza"],"aciklama":"Disiplin uyarı tutanağı"}'::jsonb);

-- ─────────────────────────────────────────────────────────────────────────────
-- CMO: 7 şablon
-- ─────────────────────────────────────────────────────────────────────────────
INSERT INTO ceo_templates (ad, kategori, icerik, durum, olusturan, template_name, template_type, content) VALUES
('Sosyal Medya Post', 'CMO', '{"tip":"tasarim","platformlar":["instagram","facebook","twitter","linkedin"],"alanlar":["baslik","metin","gorsel","hashtag","yayin_tarihi"],"aciklama":"Sosyal medya paylaşım şablonu"}', 'aktif', 'CMO', 'Sosyal Medya Post', 'rapor', '{"tip":"tasarim","platformlar":["instagram","facebook","twitter","linkedin"],"alanlar":["baslik","metin","gorsel","hashtag","yayin_tarihi"],"aciklama":"Sosyal medya paylaşım şablonu"}'::jsonb),
('Kampanya Plani', 'CMO', '{"tip":"plan","alanlar":["kampanya_adi","hedef_kitle","butee","sure","hedefler"],"platformlar":["dijital","basili","etkinlik"],"metrikler":["ulasim","tiklama","donusum"],"aciklama":"Pazarlama kampanyası planı"}', 'aktif', 'CMO', 'Kampanya Plani', 'rapor', '{"tip":"plan","alanlar":["kampanya_adi","hedef_kitle","butee","sure","hedefler"],"platformlar":["dijital","basili","etkinlik"],"metrikler":["ulasim","tiklama","donusum"],"aciklama":"Pazarlama kampanyası planı"}'::jsonb),
('E-posta Bulteni', 'CMO', '{"tip":"email","alanlar":["konu","oneri_metin","cta_metin","gorsel_url"],"aciklama":"E-posta bülteni içerik şablonu"}', 'aktif', 'CMO', 'E-posta Bulteni', 'email', '{"tip":"email","alanlar":["konu","oneri_metin","cta_metin","gorsel_url"],"aciklama":"E-posta bülteni içerik şablonu"}'::jsonb),
('Tanitim Brosuru', 'CMO', '{"tip":"tasarim","bolumler":["kapak","hakkimizda","hizmetler","fiyatlar","iletisim"],"alanlar":["brosur_adi","hedef_kitle"],"aciklama":"Kurumsal tanıtım broşürü yapısı"}', 'aktif', 'CMO', 'Tanitim Brosuru', 'rapor', '{"tip":"tasarim","bolumler":["kapak","hakkimizda","hizmetler","fiyatlar","iletisim"],"alanlar":["brosur_adi","hedef_kitle"],"aciklama":"Kurumsal tanıtım broşürü yapısı"}'::jsonb),
('Fiyat Listesi', 'CMO', '{"tip":"tablo","turler":["aylik","donemlik","ozel_paket"],"alanlar":["urun_hizmet_adi","fiyat","birim","aciklama"],"aciklama":"Ürün/hizmet fiyat listesi"}', 'aktif', 'CMO', 'Fiyat Listesi', 'rapor', '{"tip":"tablo","turler":["aylik","donemlik","ozel_paket"],"alanlar":["urun_hizmet_adi","fiyat","birim","aciklama"],"aciklama":"Ürün/hizmet fiyat listesi"}'::jsonb),
('SEO Icerik Plani', 'CMO', '{"tip":"plan","alanlar":["anahtar_kelime","baslik","meta_aciklama","icerik_ozeti","hedef_url"],"aciklama":"SEO uyumlu içerik planı"}', 'aktif', 'CMO', 'SEO Icerik Plani', 'rapor', '{"tip":"plan","alanlar":["anahtar_kelime","baslik","meta_aciklama","icerik_ozeti","hedef_url"],"aciklama":"SEO uyumlu içerik planı"}'::jsonb),
('Blog Yazisi', 'CMO', '{"tip":"rehber","alanlar":["baslik","giris","ana_bolumler","sonuc","cta"],"aciklama":"Blog yazısı yapı şablonu"}', 'aktif', 'CMO', 'Blog Yazisi', 'rapor', '{"tip":"rehber","alanlar":["baslik","giris","ana_bolumler","sonuc","cta"],"aciklama":"Blog yazısı yapı şablonu"}'::jsonb);

-- ─────────────────────────────────────────────────────────────────────────────
-- CTO: 5 şablon
-- ─────────────────────────────────────────────────────────────────────────────
INSERT INTO ceo_templates (ad, kategori, icerik, durum, olusturan, template_name, template_type, content) VALUES
('API Dokumantasyonu', 'CTO', '{"tip":"rehber","alanlar":["endpoint","method","parametreler","ornek_istek","ornek_yanit","hata_kodlari"],"aciklama":"API endpoint dokümantasyon şablonu"}', 'aktif', 'CTO', 'API Dokumantasyonu', 'rapor', '{"tip":"rehber","alanlar":["endpoint","method","parametreler","ornek_istek","ornek_yanit","hata_kodlari"],"aciklama":"API endpoint dokümantasyon şablonu"}'::jsonb),
('Deployment Checklist', 'CTO', '{"tip":"checklist","kontroller":["test_geçti","env_degiskenleri","veritabani_migration","yedek_alindi","rollback_plani"],"alanlar":["versiyon","tarih","sorumlu"],"aciklama":"Canlıya alma öncesi kontrol listesi"}', 'aktif', 'CTO', 'Deployment Checklist', 'rapor', '{"tip":"checklist","kontroller":["test_geçti","env_degiskenleri","veritabani_migration","yedek_alindi","rollback_plani"],"alanlar":["versiyon","tarih","sorumlu"],"aciklama":"Canlıya alma öncesi kontrol listesi"}'::jsonb),
('Hata Raporu', 'CTO', '{"tip":"rapor","alanlar":["hata_ozeti","adimlar","ortam","oncelik","durum"],"aciklama":"Teknik hata raporlama şablonu"}', 'aktif', 'CTO', 'Hata Raporu', 'rapor', '{"tip":"rapor","alanlar":["hata_ozeti","adimlar","ortam","oncelik","durum"],"aciklama":"Teknik hata raporlama şablonu"}'::jsonb),
('Veritabani Sema', 'CTO', '{"tip":"rehber","alanlar":["tablo_adi","kolonlar","iliskiler","indexler","aciklama"],"aciklama":"Veritabanı şema dokümantasyonu"}', 'aktif', 'CTO', 'Veritabani Sema', 'rapor', '{"tip":"rehber","alanlar":["tablo_adi","kolonlar","iliskiler","indexler","aciklama"],"aciklama":"Veritabanı şema dokümantasyonu"}'::jsonb),
('Sistem Durum Raporu', 'CTO', '{"tip":"rapor","metrikler":["uptime","yanit_suresi","hata_orani","kullanim"],"alanlar":["donem","ozet","onlemler"],"aciklama":"Sistem sağlık raporu"}', 'aktif', 'CTO', 'Sistem Durum Raporu', 'rapor', '{"tip":"rapor","metrikler":["uptime","yanit_suresi","hata_orani","kullanim"],"alanlar":["donem","ozet","onlemler"],"aciklama":"Sistem sağlık raporu"}'::jsonb);

-- ─────────────────────────────────────────────────────────────────────────────
-- CSO: 5 şablon
-- ─────────────────────────────────────────────────────────────────────────────
INSERT INTO ceo_templates (ad, kategori, icerik, durum, olusturan, template_name, template_type, content) VALUES
('Satis Scripti', 'CSO', '{"tip":"script","bolumler":["acilis","ihtiyac_analizi","sunum","itirazlar","kapanis"],"alanlar":["hedef_kitle","ana_mesaj"],"aciklama":"Satış görüşmesi script yapısı"}', 'aktif', 'CSO', 'Satis Scripti', 'rapor', '{"tip":"script","bolumler":["acilis","ihtiyac_analizi","sunum","itirazlar","kapanis"],"alanlar":["hedef_kitle","ana_mesaj"],"aciklama":"Satış görüşmesi script yapısı"}'::jsonb),
('Teklif Mektubu', 'CSO', '{"tip":"belge","alanlar":["musteri_adi","teklif_no","gecerlilik","kalemler","toplam","kosullar"],"aciklama":"Müşteriye sunulan teklif metni"}', 'aktif', 'CSO', 'Teklif Mektubu', 'rapor', '{"tip":"belge","alanlar":["musteri_adi","teklif_no","gecerlilik","kalemler","toplam","kosullar"],"aciklama":"Müşteriye sunulan teklif metni"}'::jsonb),
('Lead Takip', 'CSO', '{"tip":"tablo","alanlar":["lead_adi","kaynak","durum","son_iletisim","sonraki_adim"],"aciklama":"Potansiyel müşteri takip tablosu"}', 'aktif', 'CSO', 'Lead Takip', 'rapor', '{"tip":"tablo","alanlar":["lead_adi","kaynak","durum","son_iletisim","sonraki_adim"],"aciklama":"Potansiyel müşteri takip tablosu"}'::jsonb),
('Demo Sunum Plani', 'CSO', '{"tip":"plan","bolumler":["tanisma","sorun_tanimi","cozum_sunumu","fiyat","soru_cevap","kapanis"],"alanlar":["sure_dakika","sorumlu"],"aciklama":"Demo sunumu akış planı"}', 'aktif', 'CSO', 'Demo Sunum Plani', 'rapor', '{"tip":"plan","bolumler":["tanisma","sorun_tanimi","cozum_sunumu","fiyat","soru_cevap","kapanis"],"alanlar":["sure_dakika","sorumlu"],"aciklama":"Demo sunumu akış planı"}'::jsonb),
('Satis Raporu', 'CSO', '{"tip":"rapor","metrikler":["hedef","gerceklesen","fark","yeni_musteri","ciro"],"alanlar":["donem","ozet"],"aciklama":"Dönemsel satış performans raporu"}', 'aktif', 'CSO', 'Satis Raporu', 'rapor', '{"tip":"rapor","metrikler":["hedef","gerceklesen","fark","yeni_musteri","ciro"],"alanlar":["donem","ozet"],"aciklama":"Dönemsel satış performans raporu"}'::jsonb);

-- ─────────────────────────────────────────────────────────────────────────────
-- CSPO: 6 şablon
-- ─────────────────────────────────────────────────────────────────────────────
INSERT INTO ceo_templates (ad, kategori, icerik, durum, olusturan, template_name, template_type, content) VALUES
('Ders Programi', 'CSPO', '{"tip":"tablo","alanlar":["gun","saat","brans","yas_grubu","antrenor","salon"],"branslar":["jimnastik","yuzme","basketbol","futbol"],"yas_gruplari":["4-6","7-9","10-12","13+"],"aciklama":"Haftalık ders programı"}', 'aktif', 'CSPO', 'Ders Programi', 'rapor', '{"tip":"tablo","alanlar":["gun","saat","brans","yas_grubu","antrenor","salon"],"branslar":["jimnastik","yuzme","basketbol","futbol"],"yas_gruplari":["4-6","7-9","10-12","13+"],"aciklama":"Haftalık ders programı"}'::jsonb),
('Sporcu Kayit', 'CSPO', '{"tip":"form","alanlar":["ad_soyad","dogum_tarihi","veli_iletisim","brans","saglik_bilgisi","acil_durum"],"aciklama":"Yeni sporcu kayıt formu"}', 'aktif', 'CSPO', 'Sporcu Kayit', 'rapor', '{"tip":"form","alanlar":["ad_soyad","dogum_tarihi","veli_iletisim","brans","saglik_bilgisi","acil_durum"],"aciklama":"Yeni sporcu kayıt formu"}'::jsonb),
('Gelisim Raporu', 'CSPO', '{"tip":"rapor","kriterler":["teknik","fiziksel","sosyal","katilim"],"alanlar":["sporcu_adi","donem","genel_puan","yorum"],"aciklama":"Sporcu gelişim değerlendirme raporu"}', 'aktif', 'CSPO', 'Gelisim Raporu', 'rapor', '{"tip":"rapor","kriterler":["teknik","fiziksel","sosyal","katilim"],"alanlar":["sporcu_adi","donem","genel_puan","yorum"],"aciklama":"Sporcu gelişim değerlendirme raporu"}'::jsonb),
('Antrenman Plani', 'CSPO', '{"tip":"plan","branslar":["jimnastik","yuzme","basketbol"],"alanlar":["hedef","sure","icerik_ozeti","degerlendirme"],"aciklama":"Antrenman birim planı"}', 'aktif', 'CSPO', 'Antrenman Plani', 'rapor', '{"tip":"plan","branslar":["jimnastik","yuzme","basketbol"],"alanlar":["hedef","sure","icerik_ozeti","degerlendirme"],"aciklama":"Antrenman birim planı"}'::jsonb),
('Saglik Tarama', 'CSPO', '{"tip":"form","kontroller":["kalp","solunum","esneklik","boy_kilo"],"alanlar":["sporcu_adi","tarih","sonuc","oneri"],"aciklama":"Sporcu sağlık tarama formu"}', 'aktif', 'CSPO', 'Saglik Tarama', 'rapor', '{"tip":"form","kontroller":["kalp","solunum","esneklik","boy_kilo"],"alanlar":["sporcu_adi","tarih","sonuc","oneri"],"aciklama":"Sporcu sağlık tarama formu"}'::jsonb),
('Brans Yonlendirme', 'CSPO', '{"tip":"rehber","branslar":["jimnastik","yuzme","basketbol","futbol","voleybol","atletizm"],"alanlar":["yas_grubu","beceri_seviyesi","oneri_brans","gerekce"],"aciklama":"Yaş ve beceriye göre branş yönlendirme rehberi"}', 'aktif', 'CSPO', 'Brans Yonlendirme', 'rapor', '{"tip":"rehber","branslar":["jimnastik","yuzme","basketbol","futbol","voleybol","atletizm"],"alanlar":["yas_grubu","beceri_seviyesi","oneri_brans","gerekce"],"aciklama":"Yaş ve beceriye göre branş yönlendirme rehberi"}'::jsonb);

-- ─────────────────────────────────────────────────────────────────────────────
-- COO: 5 şablon
-- ─────────────────────────────────────────────────────────────────────────────
INSERT INTO ceo_templates (ad, kategori, icerik, durum, olusturan, template_name, template_type, content) VALUES
('Tesis Acilis Checklist', 'COO', '{"tip":"checklist","kontroller":["elektrik","isik","iklim","temizlik","malzeme","personel","güvenlik"],"alanlar":["tesis_adi","tarih","sorumlu"],"aciklama":"Günlük tesis açılış kontrol listesi"}', 'aktif', 'COO', 'Tesis Acilis Checklist', 'rapor', '{"tip":"checklist","kontroller":["elektrik","isik","iklim","temizlik","malzeme","personel","güvenlik"],"alanlar":["tesis_adi","tarih","sorumlu"],"aciklama":"Günlük tesis açılış kontrol listesi"}'::jsonb),
('Gunluk Isletme Raporu', 'COO', '{"tip":"rapor","alanlar":["tarih","ziyaretci_sayisi","ders_sayisi","olaylar","notlar"],"aciklama":"Günlük tesis işletme özeti"}', 'aktif', 'COO', 'Gunluk Isletme Raporu', 'rapor', '{"tip":"rapor","alanlar":["tarih","ziyaretci_sayisi","ders_sayisi","olaylar","notlar"],"aciklama":"Günlük tesis işletme özeti"}'::jsonb),
('Ekipman Bakim', 'COO', '{"tip":"tablo","alanlar":["ekipman_adi","son_bakim","sonraki_bakim","durum","sorumlu"],"kontroller":["gorsel","fonksiyon","guvenlik"],"aciklama":"Ekipman bakım takip tablosu"}', 'aktif', 'COO', 'Ekipman Bakim', 'rapor', '{"tip":"tablo","alanlar":["ekipman_adi","son_bakim","sonraki_bakim","durum","sorumlu"],"kontroller":["gorsel","fonksiyon","guvenlik"],"aciklama":"Ekipman bakım takip tablosu"}'::jsonb),
('Tesis Kurallari', 'COO', '{"tip":"belge","maddeler":["giris_cikis","giyim","davranis","guvenlik","acil_durum"],"aciklama":"Tesis kullanım kuralları metni"}', 'aktif', 'COO', 'Tesis Kurallari', 'rapor', '{"tip":"belge","maddeler":["giris_cikis","giyim","davranis","guvenlik","acil_durum"],"aciklama":"Tesis kullanım kuralları metni"}'::jsonb),
('Franchise Onboarding', 'COO', '{"tip":"plan","bolumler":["sozlesme","tesis_hazirlik","personel_egitim","sistem_kurulum","acilis_planı"],"alanlar":["franchise_adi","baslangic_tarihi","sorumlu"],"aciklama":"Yeni franchise devreye alma planı"}', 'aktif', 'COO', 'Franchise Onboarding', 'rapor', '{"tip":"plan","bolumler":["sozlesme","tesis_hazirlik","personel_egitim","sistem_kurulum","acilis_planı"],"alanlar":["franchise_adi","baslangic_tarihi","sorumlu"],"aciklama":"Yeni franchise devreye alma planı"}'::jsonb);

-- ─────────────────────────────────────────────────────────────────────────────
-- CMDO: 5 şablon
-- ─────────────────────────────────────────────────────────────────────────────
INSERT INTO ceo_templates (ad, kategori, icerik, durum, olusturan, template_name, template_type, content) VALUES
('Logo Tasarim Briefingi', 'CMDO', '{"tip":"brief","alanlar":["marka_adi","hedef_kitle","renk_tercihleri","referanslar","teslim_tarihi"],"aciklama":"Logo tasarımı için yaratıcı brief"}', 'aktif', 'CMDO', 'Logo Tasarim Briefingi', 'rapor', '{"tip":"brief","alanlar":["marka_adi","hedef_kitle","renk_tercihleri","referanslar","teslim_tarihi"],"aciklama":"Logo tasarımı için yaratıcı brief"}'::jsonb),
('Video Icerik Plani', 'CMDO', '{"tip":"plan","turler":["tanitim","egitim","sosyal_medya","etkinlik"],"alanlar":["baslik","sure","hedef","sahne_ozeti","cikti_format"],"aciklama":"Video prodüksiyon içerik planı"}', 'aktif', 'CMDO', 'Video Icerik Plani', 'rapor', '{"tip":"plan","turler":["tanitim","egitim","sosyal_medya","etkinlik"],"alanlar":["baslik","sure","hedef","sahne_ozeti","cikti_format"],"aciklama":"Video prodüksiyon içerik planı"}'::jsonb),
('Gorsel Standartlar', 'CMDO', '{"tip":"rehber","alanlar":["logo_kullanim","renk_paleti","fontlar","fotograf_stili","cizim_stili"],"aciklama":"Marka görsel standartları rehberi"}', 'aktif', 'CMDO', 'Gorsel Standartlar', 'rapor', '{"tip":"rehber","alanlar":["logo_kullanim","renk_paleti","fontlar","fotograf_stili","cizim_stili"],"aciklama":"Marka görsel standartları rehberi"}'::jsonb),
('Dogum Gunu Sablonu', 'CMDO', '{"tip":"tasarim","alanlar":["sporcu_adi","yas","tarih","mesaj","gorsel_ozeti"],"aciklama":"Sporcu doğum günü kutlama şablonu"}', 'aktif', 'CMDO', 'Dogum Gunu Sablonu', 'rapor', '{"tip":"tasarim","alanlar":["sporcu_adi","yas","tarih","mesaj","gorsel_ozeti"],"aciklama":"Sporcu doğum günü kutlama şablonu"}'::jsonb),
('Etkinlik Afisi', 'CMDO', '{"tip":"tasarim","alanlar":["etkinlik_adi","tarih_saat","yer","katilim_kosullari","iletisim"],"aciklama":"Etkinlik duyuru afişi yapısı"}', 'aktif', 'CMDO', 'Etkinlik Afisi', 'rapor', '{"tip":"tasarim","alanlar":["etkinlik_adi","tarih_saat","yer","katilim_kosullari","iletisim"],"aciklama":"Etkinlik duyuru afişi yapısı"}'::jsonb);

-- ─────────────────────────────────────────────────────────────────────────────
-- CCO: 4 şablon
-- ─────────────────────────────────────────────────────────────────────────────
INSERT INTO ceo_templates (ad, kategori, icerik, durum, olusturan, template_name, template_type, content) VALUES
('Sikayet Formu', 'CCO', '{"tip":"form","alanlar":["musteri_adi","iletisim","konu","aciklama","oncelik","tarih"],"aciklama":"Müşteri şikayet kayıt formu"}', 'aktif', 'CCO', 'Sikayet Formu', 'rapor', '{"tip":"form","alanlar":["musteri_adi","iletisim","konu","aciklama","oncelik","tarih"],"aciklama":"Müşteri şikayet kayıt formu"}'::jsonb),
('Memnuniyet Anketi', 'CCO', '{"tip":"anket","alanlar":["hizmet_adi","tarih"],"sorular":["genel_memnuniyet","tekrar_tercih","tavsiye","yorum"],"olcek":"1-5","aciklama":"Hizmet sonrası memnuniyet anketi"}', 'aktif', 'CCO', 'Memnuniyet Anketi', 'rapor', '{"tip":"anket","alanlar":["hizmet_adi","tarih"],"sorular":["genel_memnuniyet","tekrar_tercih","tavsiye","yorum"],"olcek":"1-5","aciklama":"Hizmet sonrası memnuniyet anketi"}'::jsonb),
('Hosgeldin Mesaji', 'CCO', '{"tip":"email","alanlar":["musteri_adi","hizmet_adi","iletisim_bilgileri","sonraki_adim"],"aciklama":"Yeni üye/müşteri karşılama e-postası"}', 'aktif', 'CCO', 'Hosgeldin Mesaji', 'email', '{"tip":"email","alanlar":["musteri_adi","hizmet_adi","iletisim_bilgileri","sonraki_adim"],"aciklama":"Yeni üye/müşteri karşılama e-postası"}'::jsonb),
('Sadakat Programi', 'CCO', '{"tip":"plan","alanlar":["program_adi","kazanim_kurallari","oduller","sure"],"aciklama":"Müşteri sadakat programı taslağı"}', 'aktif', 'CCO', 'Sadakat Programi', 'rapor', '{"tip":"plan","alanlar":["program_adi","kazanim_kurallari","oduller","sure"],"aciklama":"Müşteri sadakat programı taslağı"}'::jsonb);

-- ─────────────────────────────────────────────────────────────────────────────
-- CDO: 4 şablon
-- ─────────────────────────────────────────────────────────────────────────────
INSERT INTO ceo_templates (ad, kategori, icerik, durum, olusturan, template_name, template_type, content) VALUES
('Dashboard Metrik', 'CDO', '{"tip":"tablo","metrikler":["aktif_uye","aylik_ciro","doluluk_orani","yeni_kayit","churn"],"alanlar":["metrik_adi","deger","donem","hedef"],"aciklama":"Yönetim dashboard metrik tanımları"}', 'aktif', 'CDO', 'Dashboard Metrik', 'dashboard', '{"tip":"tablo","metrikler":["aktif_uye","aylik_ciro","doluluk_orani","yeni_kayit","churn"],"alanlar":["metrik_adi","deger","donem","hedef"],"aciklama":"Yönetim dashboard metrik tanımları"}'::jsonb),
('Sporcu Istatistik', 'CDO', '{"tip":"rapor","metrikler":["toplam_sporcu","brans_dagilimi","yas_dagilimi","yeni_kayit","ayrilan"],"alanlar":["donem","ozet"],"aciklama":"Sporcu sayı ve dağılım raporu"}', 'aktif', 'CDO', 'Sporcu Istatistik', 'rapor', '{"tip":"rapor","metrikler":["toplam_sporcu","brans_dagilimi","yas_dagilimi","yeni_kayit","ayrilan"],"alanlar":["donem","ozet"],"aciklama":"Sporcu sayı ve dağılım raporu"}'::jsonb),
('Finansal Analiz', 'CDO', '{"tip":"rapor","metrikler":["gelir","gider","kar","marj","trend"],"alanlar":["donem","karsilastirma_donem"],"aciklama":"Finansal performans analiz raporu"}', 'aktif', 'CDO', 'Finansal Analiz', 'rapor', '{"tip":"rapor","metrikler":["gelir","gider","kar","marj","trend"],"alanlar":["donem","karsilastirma_donem"],"aciklama":"Finansal performans analiz raporu"}'::jsonb),
('Tenant Karsilastirma', 'CDO', '{"tip":"rapor","alanlar":["tenant_adi","metrik_adi","deger","siralama"],"metrikler":["ciro","uye_sayisi","doluluk"],"aciklama":"Franchise/tesis karşılaştırma raporu"}', 'aktif', 'CDO', 'Tenant Karsilastirma', 'rapor', '{"tip":"rapor","alanlar":["tenant_adi","metrik_adi","deger","siralama"],"metrikler":["ciro","uye_sayisi","doluluk"],"aciklama":"Franchise/tesis karşılaştırma raporu"}'::jsonb);

-- ─────────────────────────────────────────────────────────────────────────────
-- CISO: 3 şablon
-- ─────────────────────────────────────────────────────────────────────────────
INSERT INTO ceo_templates (ad, kategori, icerik, durum, olusturan, template_name, template_type, content) VALUES
('Guvenlik Denetim', 'CISO', '{"tip":"checklist","kontroller":["sifre_politikasi","erişim_log","yedekleme","fiziksel_guvenlik","kvkk_uyum"],"alanlar":["tarih","denetci","sonuc","onlemler"],"aciklama":"Periyodik güvenlik denetim listesi"}', 'aktif', 'CISO', 'Guvenlik Denetim', 'rapor', '{"tip":"checklist","kontroller":["sifre_politikasi","erişim_log","yedekleme","fiziksel_guvenlik","kvkk_uyum"],"alanlar":["tarih","denetci","sonuc","onlemler"],"aciklama":"Periyodik güvenlik denetim listesi"}'::jsonb),
('Erisim Yetki Matrisi', 'CISO', '{"tip":"tablo","roller":["admin","yonetici","personel","veli","sporcu"],"alanlar":["sistem_bolumu","rol","okuma","yazma","silme"],"aciklama":"Rol bazlı erişim yetki matrisi"}', 'aktif', 'CISO', 'Erisim Yetki Matrisi', 'rapor', '{"tip":"tablo","roller":["admin","yonetici","personel","veli","sporcu"],"alanlar":["sistem_bolumu","rol","okuma","yazma","silme"],"aciklama":"Rol bazlı erişim yetki matrisi"}'::jsonb),
('Olay Mudahale Plani', 'CISO', '{"tip":"plan","bolumler":["tespit","bildirim","izolasyon","analiz","iyilestirme"],"alanlar":["olay_tipi","sorumlu_ekip","iletisim"],"aciklama":"Güvenlik olayı müdahale planı"}', 'aktif', 'CISO', 'Olay Mudahale Plani', 'rapor', '{"tip":"plan","bolumler":["tespit","bildirim","izolasyon","analiz","iyilestirme"],"alanlar":["olay_tipi","sorumlu_ekip","iletisim"],"aciklama":"Güvenlik olayı müdahale planı"}'::jsonb);
